
title: Modular Devices / Malleable Audio
email: info.malleable@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We make modular devices for audio creation, processing, and control, creating 
  malleable audio from modular devices. 
baseurl: "/mdma.github.io" # the subpath of your site, e.g. /blog
url: https://mdma.github.io # the base hostname & protocol for your site, e.g. http://example.com
domain: mdma.github.io # no http forces https
twitter_username: malleable808
github_username:  ModularDevicesMalleableAudio

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-feed

footer: mdma
header_pages:
  - index.md
  - projects.md
  - documentation.md
  - repos.md